import React, { useState, useEffect, useMemo } from 'react';
import LeadScout from './components/LeadScout';
import EmailWriter from './components/EmailWriter';
import { LeadCard } from './components/LeadCard';
import { AppView, LeadProfile, BackgroundReport } from './types';
import { storageService } from './services/storageService';
import { generateBackgroundReport } from './services/qwenService'; // Switched to Qwen

// Report Modal Component (Lifted from LeadScout)
const ReportModal = ({ 
  report, 
  loading, 
  onClose,
  onWriteEmail
}: { 
  report: BackgroundReport | null, 
  loading: boolean, 
  onClose: () => void,
  onWriteEmail: (report: BackgroundReport) => void
}) => {
  if (!report && !loading) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[85vh] flex flex-col overflow-hidden animate-fade-in-up">
        {/* Header */}
        <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50">
          <div>
            <h3 className="text-xl font-bold text-slate-900">
              {loading ? "Generating Report..." : `${report?.companyName} - 深度背调报告`}
            </h3>
            {!loading && <p className="text-sm text-slate-500 mt-1">Generated by TradeFlow AI (Qwen) • Sources: Web Search</p>}
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 p-2">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8">
          {loading ? (
             <div className="flex flex-col items-center justify-center h-64 space-y-4">
               <div className="w-12 h-12 border-4 border-slate-200 border-t-blue-600 rounded-full animate-spin"></div>
               <p className="text-slate-600 font-medium">Analyzing company footprint...</p>
               <p className="text-xs text-slate-400">Searching financial data, product lines, and market reputation.</p>
             </div>
          ) : report ? (
             <div className="space-y-8">
               <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 <div className="bg-blue-50 p-5 rounded-xl border border-blue-100">
                    <h4 className="font-bold text-blue-800 mb-2 flex items-center gap-2">
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path></svg>
                      公司概况 (Overview)
                    </h4>
                    <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{report.overview}</p>
                 </div>
                 <div className="bg-purple-50 p-5 rounded-xl border border-purple-100">
                    <h4 className="font-bold text-purple-800 mb-2 flex items-center gap-2">
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path></svg>
                      主营产品 (Products)
                    </h4>
                    <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{report.products}</p>
                 </div>
               </div>

               <div>
                 <h4 className="font-bold text-slate-800 mb-2 border-b border-slate-200 pb-2">市场地位与竞争 (Market Position)</h4>
                 <p className="text-slate-600 leading-relaxed">{report.marketPosition}</p>
               </div>

               {report.financialStatus && (
                 <div>
                   <h4 className="font-bold text-slate-800 mb-2 border-b border-slate-200 pb-2">经营状况 (Financial Status)</h4>
                   <p className="text-slate-600 leading-relaxed">{report.financialStatus}</p>
                 </div>
               )}

               <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-4">
                  <div>
                    <h4 className="font-bold text-red-600 mb-2 flex items-center gap-2">
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                      风险评估 (Risks)
                    </h4>
                    <p className="text-sm text-slate-600 bg-red-50 p-3 rounded-lg border border-red-100">{report.riskAssessment || "未发现重大公开风险。"}</p>
                  </div>
                  <div>
                    <h4 className="font-bold text-green-600 mb-2 flex items-center gap-2">
                       <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                       合作建议 (Suggestion)
                    </h4>
                    <p className="text-sm text-slate-600 bg-green-50 p-3 rounded-lg border border-green-100">{report.cooperationSuggestion}</p>
                  </div>
               </div>
             </div>
          ) : null}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-100 bg-slate-50 flex justify-end gap-3">
           <button 
             onClick={onClose}
             className="px-4 py-2 text-slate-600 hover:text-slate-900 font-medium"
           >
             Close
           </button>
           {report && (
             <>
                <button 
                  onClick={() => {
                    const text = `Company: ${report.companyName}\n\nOverview:\n${report.overview}\n\nProducts:\n${report.products}\n\nMarket:\n${report.marketPosition}\n\nSuggestion:\n${report.cooperationSuggestion}`;
                    navigator.clipboard.writeText(text);
                    alert("Report copied to clipboard");
                  }}
                  className="px-4 py-2 text-slate-700 hover:text-slate-900 border border-slate-300 rounded-lg hover:border-slate-400 font-medium"
                >
                  Copy Report
                </button>
                <button 
                  onClick={() => onWriteEmail(report)}
                  className="bg-primary text-white px-5 py-2 rounded-lg hover:bg-blue-600 font-medium flex items-center gap-2 shadow-sm"
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
                  Write Targeted Email
                </button>
             </>
           )}
        </div>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState<AppView>(AppView.LEAD_SCOUT);
  const [currentLead, setCurrentLead] = useState<LeadProfile | null>(null);
  const [emailContextReport, setEmailContextReport] = useState<BackgroundReport | null>(null);
  const [historyLeads, setHistoryLeads] = useState<LeadProfile[]>([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  
  // State for email draft to persist across view switches
  const [emailDraft, setEmailDraft] = useState<{subject: string, body: string}>({ subject: '', body: '' });

  // State for Lead Scout results to persist across view switches
  const [scoutState, setScoutState] = useState<{query: string; leads: LeadProfile[]}>({
    query: '',
    leads: []
  });

  // Report Modal State
  const [reportModalOpen, setReportModalOpen] = useState(false);
  const [reportLoading, setReportLoading] = useState(false);
  const [activeReport, setActiveReport] = useState<BackgroundReport | null>(null);

  // Load history on mount
  useEffect(() => {
    refreshHistory();
  }, []);

  const refreshHistory = async () => {
    const leads = await storageService.getLeads();
    setHistoryLeads(leads);
  };

  // Group leads by Country
  const groupedLeads = useMemo(() => {
    return historyLeads.reduce((acc, lead) => {
      // Clean up country string slightly if needed (e.g., trim)
      const region = lead.country ? lead.country.trim() : 'Unspecified';
      if (!acc[region]) {
        acc[region] = [];
      }
      acc[region].push(lead);
      return acc;
    }, {} as Record<string, LeadProfile[]>);
  }, [historyLeads]);

  const handleLeadAction = (lead: LeadProfile) => {
    setCurrentLead(lead);
    setEmailContextReport(null); // Reset report context if coming from list
    setCurrentView(AppView.EMAIL_WRITER);
  };

  const handleDeleteLead = async (name: string) => {
    await storageService.deleteLead(name);
    await refreshHistory();
    
    // Also remove from current view if present
    const currentFiltered = scoutState.leads.filter(l => l.companyName !== name);
    if (currentFiltered.length !== scoutState.leads.length) {
      setScoutState({ ...scoutState, leads: currentFiltered });
    }
  };

  const handleGenerateReport = async (lead: LeadProfile) => {
    // If we are already viewing the lead, keep it, otherwise update it
    setCurrentLead(lead); 
    setReportModalOpen(true);
    setReportLoading(true);
    setActiveReport(null);

    try {
      const report = await generateBackgroundReport(lead);
      setActiveReport(report);
    } catch (e: any) {
      alert("Failed to generate report: " + e.message);
      setReportModalOpen(false);
    } finally {
      setReportLoading(false);
    }
  };

  const handleWriteEmailFromReport = (report: BackgroundReport) => {
    setEmailContextReport(report);
    setReportModalOpen(false);
    setCurrentView(AppView.EMAIL_WRITER);
    // currentLead is already set when opening the report modal
  };

  const renderContent = () => {
    switch (currentView) {
      case AppView.LEAD_SCOUT:
        return <LeadScout 
          onLeadFound={handleLeadAction} 
          savedState={scoutState}
          onSaveState={setScoutState}
          onRefreshHistory={refreshHistory}
          onGenerateReport={handleGenerateReport}
        />;
      case AppView.EMAIL_WRITER:
        return <EmailWriter 
          currentLead={currentLead} 
          backgroundReport={emailContextReport}
          draft={emailDraft}
          onUpdateDraft={setEmailDraft}
        />;
      default:
        return <LeadScout 
          onLeadFound={handleLeadAction}
          savedState={scoutState}
          onSaveState={setScoutState}
          onRefreshHistory={refreshHistory}
          onGenerateReport={handleGenerateReport}
        />;
    }
  };

  return (
    <div className="flex h-screen bg-slate-50 relative">
      {/* Modal is global now */}
      {reportModalOpen && (
        <ReportModal 
          report={activeReport} 
          loading={reportLoading} 
          onClose={() => setReportModalOpen(false)} 
          onWriteEmail={handleWriteEmailFromReport}
        />
      )}

      {/* Left Sidebar (Navigation) */}
      <aside className="w-64 bg-slate-900 text-slate-300 flex-shrink-0 flex flex-col z-20">
        <div className="p-6">
          <div className="flex items-center gap-2 text-white font-bold text-xl tracking-tight">
            <svg className="w-8 h-8 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
            TradeFlow AI
          </div>
        </div>

        <nav className="flex-1 px-4 space-y-2 mt-4">
          <button
            onClick={() => setCurrentView(AppView.LEAD_SCOUT)}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors ${
              currentView === AppView.LEAD_SCOUT
                ? 'bg-blue-600 text-white'
                : 'hover:bg-slate-800'
            }`}
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
            Lead Scout
          </button>

          <button
            onClick={() => setCurrentView(AppView.EMAIL_WRITER)}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors ${
              currentView === AppView.EMAIL_WRITER
                ? 'bg-blue-600 text-white'
                : 'hover:bg-slate-800'
            }`}
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path></svg>
            Email Writer
            {currentLead && <span className="w-2 h-2 bg-green-500 rounded-full ml-auto"></span>}
          </button>
        </nav>

        <div className="p-4 border-t border-slate-800">
           <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500"></div>
              <div>
                <div className="text-sm font-medium text-white">Merchant User</div>
                <div className="text-xs text-slate-500">Pro Plan</div>
              </div>
           </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-hidden flex flex-col relative z-0">
        <header className="h-16 border-b border-slate-200 bg-white flex-shrink-0 flex items-center justify-between px-6">
            <h1 className="text-lg font-semibold text-slate-800">
              {currentView === AppView.LEAD_SCOUT && 'Market Intelligence'}
              {currentView === AppView.EMAIL_WRITER && 'Outreach Generation'}
            </h1>
            <div className="flex items-center gap-4">
               {currentLead && currentView !== AppView.LEAD_SCOUT && (
                 <span className="text-xs bg-blue-50 text-blue-600 px-2 py-1 rounded border border-blue-100">
                   Active Lead: {currentLead.companyName}
                 </span>
               )}
               
               {/* Sidebar Toggle Button */}
               <button 
                 onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                 className={`p-2 rounded-lg transition-colors ${isSidebarOpen ? 'bg-slate-100 text-primary' : 'hover:bg-slate-100 text-slate-500'}`}
                 title={isSidebarOpen ? "Hide Library" : "Show Leads Library"}
               >
                 <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
               </button>
            </div>
        </header>
        <div className="flex-1 overflow-auto">
          {renderContent()}
        </div>
      </main>

      {/* Right Sidebar (Leads Library) */}
      <aside className={`${isSidebarOpen ? 'w-80 border-l' : 'w-0'} bg-white flex-shrink-0 flex flex-col z-10 shadow-xl transition-all duration-300 ease-in-out border-slate-200 overflow-hidden`}>
         <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50 min-w-[20rem]">
            <h3 className="font-bold text-slate-800 flex items-center gap-2">
              <svg className="w-4 h-4 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 19a2 2 0 01-2-2V7a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1M5 19h14a2 2 0 002-2v-5a2 2 0 00-2-2H9a2 2 0 00-2 2v5a2 2 0 01-2 2z"></path></svg>
              Leads Library <span className="text-xs text-slate-400 font-normal">({historyLeads.length})</span>
            </h3>
            {historyLeads.length > 0 && (
              <button 
                onClick={async () => {
                  if(confirm("Clear library?")) {
                    await storageService.clearAll();
                    refreshHistory();
                  }
                }}
                className="text-xs text-slate-400 hover:text-red-500"
              >
                Clear
              </button>
            )}
         </div>
         
         <div className="flex-1 overflow-y-auto p-3 space-y-4 bg-slate-50/50 min-w-[20rem]">
            {historyLeads.length === 0 ? (
              <div className="text-center py-10 opacity-50">
                <p className="text-sm text-slate-400">No leads saved yet.</p>
              </div>
            ) : (
              // Render grouped leads
              Object.entries(groupedLeads).map(([region, leads]: [string, LeadProfile[]]) => (
                <details key={region} open className="group">
                  <summary className="flex items-center gap-2 cursor-pointer list-none py-1 mb-2">
                    <span className="text-slate-400 group-open:rotate-90 transition-transform duration-200">
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M9 5l7 7-7 7"></path></svg>
                    </span>
                    <span className="font-bold text-sm text-slate-700">{region}</span>
                    <span className="text-xs text-slate-400 bg-slate-100 px-1.5 py-0.5 rounded-full">{leads.length}</span>
                  </summary>
                  
                  <div className="space-y-3 pl-2 border-l border-slate-200 ml-1.5">
                    {leads.map((lead, idx) => (
                      <LeadCard 
                        key={`${region}-${idx}`}
                        lead={lead}
                        isCompact={true}
                        onSelect={handleLeadAction}
                        onDelete={handleDeleteLead}
                        onGenerateReport={handleGenerateReport}
                      />
                    ))}
                  </div>
                </details>
              ))
            )}
         </div>
      </aside>
    </div>
  );
};

export default App;